version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contentflow
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: .
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/contentflow
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      PORT: 8000
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  worker:
    build: .
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/contentflow
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      - db
      - redis
    command: ["celery", "-A", "app.workers.celery_app:celery_app", "worker", "--loglevel=info"]

volumes:
  pgdata:
