# ContentFlow • API + (optionnel) Worker
[build]
builder = "NIXPACKS"

[env]
PYTHON_VERSION = "3.11"
NIXPACKS_PKGS  = "ffmpeg"
PORT           = "8080"

# -------- API (FastAPI/Uvicorn) --------
[service.api]
root  = "."
start = "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/healthz"
autoDeploy = true

# -------- Worker (APScheduler) — optionnel --------
[service.worker]
root  = "."
start = "python -m app.workers.autopilot"
restartPolicyType = "ON_FAILURE"
