## ContentFlow • Railway deployment via Dockerfile
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
# Leave default to follow Dockerfile CMD (start.sh wrapper).
# To force explicitly, uncomment:
# startCommand = "sh -c '/usr/local/bin/start.sh'"
