## ContentFlow • Railway deployment via Dockerfile
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
# Leave CMD from Dockerfile to control start. To force explicitly, uncomment:
# startCommand = "sh -c '/usr/local/bin/start.sh'"
