## ContentFlow • Railway deployment via Dockerfile
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
# Force explicit start to wrapper (ensures $PORT expansion under Railway)
startCommand = "sh -c '/usr/local/bin/start.sh'"
